# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=256)),
                ('reply_address', models.EmailField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=8192)),
                ('html', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
