# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 14:18
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import teachers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, verbose_name='Name')),
                ('deadline', models.DateField()),
                ('blocker', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('file', models.FileField(upload_to='media/assignments/%Y')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=2000, verbose_name='Feedback')),
                ('comments', models.TextField(max_length=2000, verbose_name='Comments')),
                ('grade', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4, verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/deliveries/%Y')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Assignment')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_stdout', models.CharField(blank=True, max_length=10240)),
                ('exit_value', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('SUCCESSFUL', 'SUCCESSFUL'), ('UNKNOWN', 'UNKNOWN')], default=teachers.models.RevisionStatus('PENDING'), max_length=16, verbose_name='Status')),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='teachers.Delivery')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=128, upload_to='media/scripts/%Y')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True, verbose_name='Padron')),
            ],
        ),
        migrations.CreateModel(
            name='Suscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=32)),
                ('suscription_date', models.DateField(default=django.utils.timezone.now)),
                ('resolve_date', models.DateField(null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Shift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50, verbose_name='Rank')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='corrector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='shifts',
            field=models.ManyToManyField(to='teachers.Shift'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='corrector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.Student'),
        ),
        migrations.AddField(
            model_name='correction',
            name='corrector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.Teacher'),
        ),
        migrations.AddField(
            model_name='correction',
            name='delivery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.Delivery'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.Course'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set([('name', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set([('uid', 'course')]),
        ),
    ]
